fix cert test to use manager namespace
k8snetworkplumbingwg/kubemacpool pull request #240
Opened 2020-08-24 14:12 UTC by RamLavi

**What this PR does / why we need it**:
Currently the cert test uses specific manager namespace
that will only be correct if running on kubemacpool repo.
Let fix by using managerNamespace which gets the real namespace
from the cluster at  the begining of the test suite.

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

2020-08-24 14:14 UTC, phoracek requested changes

2020-08-24 14:26 UTC, RamLavi commented on tests/certificates_test.go
> -	err := testClient.VirtClient.Get(context.TODO(), client.ObjectKey{Namespace: names.MANAGER_NAMESPACE, Name: names.WEBHOOK_SERVICE}, &secret)
Done

2020-08-24 14:28 UTC, qinqon commented
/lgtm
/approve

2020-08-24 14:33 UTC, qinqon commented
/hold 
@RamLavi can you prepare a test PR at CNAO pointing to here to check tier1 lane ?

2020-08-24 14:43 UTC, RamLavi commented
> /hold
> @RamLavi can you prepare a test PR at CNAO pointing to here to check tier1 lane ?

This fix is needed anyway, so I don't see a reason to add a PR to point to this PR..
so once it's merged I can retest one of my current open PRs on CNAO to make sure it  works.

Does that work for you?

2020-08-24 15:05 UTC, qinqon commented
/hold cancel

2020-08-24 15:32 UTC, RamLavi commented
/retest

2020-08-24 16:22 UTC, merged

2020-08-26 16:26 UTC, RamLavi commented
/cherry-pick release-v0.14.0