Bump kubemacpool deps
k8snetworkplumbingwg/kubemacpool pull request #244
Opened 2020-09-14 08:02 UTC by rhrazdil

Bumping versions of used dependencies.

**What this PR does / why we need it**:

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

2020-09-14 12:49 UTC, RamLavi commented
/ok-to-test

2020-09-14 13:08 UTC, RamLavi requested changes
we also need to :
- bump kubeivrt in [cluster-up script](https://github.com/k8snetworkplumbingwg/kubemacpool/blob/7600ea1e8a945a5665071bdc7e6d8619adb65195/cluster/up.sh#L28)
- bump CNAO to v1 in [cna-cr.yaml](https://github.com/k8snetworkplumbingwg/kubemacpool/blob/master/hack/cna/cna-cr.yaml) (in another commit)

2020-09-14 13:08 UTC, RamLavi commented on go.mod
> +	kubevirt.io/kubevirt v0.32.0
need to also update kubevirt in [cluster-up script](https://github.com/k8snetworkplumbingwg/kubemacpool/blob/7600ea1e8a945a5665071bdc7e6d8619adb65195/cluster/up.sh#L28)

2020-09-16 07:02 UTC, RamLavi commented
/lgtm

2020-09-16 07:09 UTC, rhrazdil commented
depends on https://github.com/kubevirt/cluster-network-addons-operator/pull/553 to be merged

2020-09-16 07:17 UTC, RamLavi commented
> depends on [kubevirt/cluster-network-addons-operator#553](https://github.com/kubevirt/cluster-network-addons-operator/pull/553) to pass the CI

do you mean that this PR need to be merged in order for [kubevirt/cluster-network-addons-operator#553](https://github.com/kubevirt/cluster-network-addons-operator/pull/553) to pass **its** CI?

2020-09-16 07:19 UTC, RamLavi commented
@qinqon do you think there is another dependency worth bumping?

2020-09-16 07:21 UTC, rhrazdil commented
@RamLavi  The other way around. kubevirt/cluster-network-addons-operator#553 needs to get in in order for this to PR to pass CI

2020-09-16 07:23 UTC, qinqon commented on go.mod
> +	// Pinned to kubernetes-0.19.1
1.19.1

2020-09-16 08:02 UTC, rhrazdil commented on go.mod
> +	// Pinned to kubernetes-0.19.1
Fixed

2020-09-16 09:45 UTC, phoracek commented
We need to get https://github.com/kubevirt/project-infra/pull/635 in first

2020-09-17 12:33 UTC, phoracek commented
@rhrazdil since the kubevirtci issue will take some time to resolve, could you drop it from this PR? Sorry for the inconvenience.

2020-09-17 12:34 UTC, qinqon commented
@phoracek fix has just merged we can update kubevirtci again and it should work

2020-09-17 12:35 UTC, phoracek commented
Excellent! Thanks for the update.

2020-09-21 07:09 UTC, rhrazdil commented
/retest

2020-09-21 12:38 UTC, rhrazdil commented
/retest

2020-09-21 14:17 UTC, RamLavi commented
/lgtm

2020-09-21 14:17 UTC, RamLavi commented
/approve

2020-09-21 14:19 UTC, merged