manager, Reduce toleration in case of node reboot
k8snetworkplumbingwg/kubemacpool pull request #374
Opened 2022-11-02 17:31 UTC by RamLavi

**What this PR does / why we need it**:
Currently if the node upon which KMP-manager deployment runs reboots, the KMP pod is evicted only 5 minutes (default) after the node is unreachable. Since KMP-manager deployment is is essential for VM create/update service-ability, reducing this eviction to 1 minute.

This means that if the node is not available/ready for more than 1 minute, the pod will evict and will try to reschedule using the configured affinity.

**Special notes for your reviewer**:

**Release note**:

```release-note
Reduce Kubemacpool-manager node eviction timeout
```

2022-11-02 17:35 UTC, RamLavi commented
I checked this PR on U/S cluster manually by 
1. deploying KMP on a 2 node cluster
2. moving KMP to node X
3. on docker pausing node X container
4. waiting until node X status is set to NotReady
5. counting 1 minutes and expecting the pod to evict to the other node

2022-11-02 17:36 UTC, RamLavi commented
/retest

2022-11-03 11:17 UTC, RamLavi commented
/cc @ormergi

2022-11-03 12:53 UTC, orelmisan reviewed
Hi @RamLavi, please consider adding a reference to the relevant K8s documentation to the PR description:
https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/#taint-based-evictions

2022-11-03 12:58 UTC, RamLavi commented
> Hi @RamLavi, please consider adding a reference to the relevant K8s documentation to the PR description: https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/#taint-based-evictions

Done

2022-11-03 13:22 UTC, orelmisan approved these changes

2022-11-03 14:13 UTC, RamLavi commented
failed test errored on BadRequest from the server, and it doesn't seem related. I want to rerun the lane a few times to be sure
/test pull-kubemacpool-e2e-k8s

2022-11-03 15:26 UTC, ormergi approved these changes

2022-11-06 11:53 UTC, qinqon requested changes
Can we add some e2e test ? It's a  important feature

2022-11-07 06:48 UTC, qinqon approved these changes
/lgtm
/approve

2022-11-07 06:49 UTC, merged